# If you do not have OpenSSL installed, update
# the following line to use "http://" instead
source 'https://rubygems.org'

gem "middleman", "~>3.3.12"

# Live-reloading plugin
gem "middleman-livereload", "~> 3.1.0"

gem "middleman-deploy"

gem "middleman-blog", "~> 3.5.1"
gem "middleman-target", "~> 0.0.6"

# Live-reloading plugin
gem "middleman-livereload", "~> 3.1.0"

# For Slim
gem "slim"

# For Markdown
gem "redcarpet", "~> 3.1.1"

# For blog summary
gem "nokogiri"

# For feed.xml.builder/sitemap.xml.builder
gem "builder", "~> 3.0"
